### ISSUE TITLE
"Error: The popup was closed for an unexpected reason" w/ Discord

### ISSUE THREAD

**Issue by colecrouter** [okteto/react-oauth2-login#4]
Using a Discord token grant doesn't seem to work properly (I had it working before, but I've updated to 0.0.7 and adjusted some of my code, and it no longer seems to work). Upon opening the popup, this immediately logs:
```
Error: The popup was closed for an unexpected reason
```
I can go through the whole auth flow just fine, and get redirected as expect. Only difference is that the popup doesn't close after.

You can check it out [here](https://breensquad.ca/discord/) on my site.

I've considered that I messed up on my end, so here's my snippet
```js
<OAuth2Login
    authorizationUrl={process.env.REACT_APP_OAUTH_TOKEN_URL}
    responseType="token"
    clientId={process.env.REACT_APP_OAUTH_CLIENT_ID}
    redirectUri={process.env.REACT_APP_OAUTH_REDIRECT_URI}
    scope="identify guilds"
    onSuccess={onSuccess}
    onFailure={onFailure} class="login" />
</>
```
The auth url seems good to me:
`https://discord.com/oauth2/authorize?client_id=<sample_id>&scope=identify%20guilds&redirect_uri=https://<sample_url>/&response_type=token`

**Comment by rlamana** [comment]
@Mexican-Man is `REACT_APP_OAUTH_REDIRECT_URI` pointing to the same domain as your app's? The main browser window will poll to check the URL of the popup window to extract the token of the transaction, but it can only access it if the URL is on the same domain.

**Comment by colecrouter** [comment]
Yup, `REACT_APP_OAUTH_REDIRECT_URI` is set to the same URL as I linked about (it redirects back to itself). I tried both with and without the trailing slash.

**Comment by rlamana** [comment]
I think the issue might be that you are trying to use an implicit grant instead of an authorization code. The library at this moment doesn't support this response type. Could you try using `responseType="code"` and see if the flow works as expected? We'll be working on supporting the implicit grant flow soon.

**Comment by colecrouter** [comment]
I tried with `responseType="code"`; the code is returned successfully, but it seems to be doing the same thing as before.
*just double checking to make sure I'm on the latest version, 0.5.0 right?

**Comment by rlamana** [comment]
Check the npm package of your dependency (https://www.npmjs.com/package/@okteto/react-oauth2-login), our latest version is `0.0.7`. There is no `0.5.0`.

**Comment by rlamana** [comment]
What do you mean by "doing the same"? the popup is not closed and it is still showing the "Error: The popup was closed for an unexpected reason" message in the console?

How can you tell that the code is returned successfully then? Does the main window receive it?

**Comment by colecrouter** [comment]
Sorry for the confusion. In the popup window, I see the `?code=` is being returned. The same `Error: The popup was closed for an unexpected reason` is occurring. It seems like the main windows does not see it. The link I posted in the original post is live & updated; you can try it for yourself to see the output.

EDIT: about the version, I'm not sure why `npm outdated` was returning 0.5.0, but my `package.json` says `0.0.7`, so I should be good. I am probably just doing it wrong.

If I was using the same version as I was in my working commit, it's more than likely that one of my recent changes caused the issue. I'll try to revert my changes in the morning and see if I can find the cause.

**Comment by rlamana** [comment]
@Mexican-Man Inspecting the code in the link you posted I realized that the dependency you are using is actually https://www.npmjs.com/package/react-simple-oauth2-login and not our library. It is also based on https://github.com/checkr/react-github-login and the code is very similar (that's probably the reason why you had the version 0.5.0). You can also tell because the return error message is different.

<img width="238" alt="Screenshot 2021-08-26 at 16 02 50" src="https://user-images.githubusercontent.com/237819/130976880-e77719b7-7077-42c9-ac4d-08b52a5cd8fa.png">
Try to contact them, or try if with our library it works for you.

**Comment by colecrouter** [comment]
AH I knew I had something wrong when I noticed that "authorizeUri" was different from what was documented. Turns out I had both libraries imported, and vscode refactored it to import the other one. My bad.

However, I've reverted back and I still seem to be getting the same issue. Here is the import, in devtools so I know I have the right library:
![image](https://user-images.githubusercontent.com/15883173/131035584-9b6a0f89-bb88-476b-914e-12e20a9039bf.png)

I double checked that the `OAuth2Login.js` being imported on the live site is the exact same one located in `@okteto/react-oauth2-login/dist/OAuth2Login.js` Now I have what should be the right error(?):

![image](https://user-images.githubusercontent.com/15883173/131036688-b1ae5f1f-43dc-4ad0-9327-2d84ba4b3410.png)

EDIT: for reference, here is my current component (I think that's the right term):
```html
            <>
                <OAuth2Login
                authorizeUri={process.env.REACT_APP_OAUTH_TOKEN_URL}
                responseType="code"
                clientId={process.env.REACT_APP_OAUTH_CLIENT_ID}
                redirectUri={process.env.REACT_APP_OAUTH_REDIRECT_URI}
                scope="identify guilds"
                onSuccess={onSuccess}
                onFailure={onFailure} class="login" />
            </>
```

**Comment by rlamana** [comment]
It seems both libraries have the same issue 🤣 But to be honest I'm having a hard time trying to repro the issue. I got it working with this setup:

```
<OAuth2
    authorizeUri="https://discord.com/oauth2/authorize"
    responseType="code"
    clientId="XXXXX"
    redirectUri="...mydomain..."
    scope="identify guilds"
    onSuccess={onSuccess}
    onFailure={onFailure}
  />
```

It is interesting to see that in your setup the error message appears right after the popup is open and it remains that way. That error is thrown when there is no reference to the popup window, assuming that it is closed. I cannot think of anything at this point that makes it enter in that condition: https://github.com/okteto/react-oauth2-login/blob/05a67696e015b646401879baeff6745576c305e8/src/PopupWindow.js#L27

**Comment by colecrouter** [comment]
Seems to be related to CORS. What I'm doing that breaks it:
``` yaml
Cross-Origin-Opener-Policy: same-origin-allow-popups
Cross-Origin-Embedder-Policy: require-corp
```
Unfortunately my site requires `SharedArrayBuffer` which requires CORS to be enabled. I've gone ahead and signed up for
[Origin Trials](https://developer.chrome.com/origintrials/#/view_trial/303992974847508481)

That has temporarily fixed the issue with discord.com. However, now the window is not recognizing the redirect url as its own. It's doing the same thing as before, except instead of reporting closed once discord is opened, it reports closed after redirecting back to my page. I tried adding `Access-Control-Allow-Origin: https://discord.com` but that didn't change anything. The last "poll" returns the discord.com link with `closed: true`, and then the next poll returns that error.

I can't think of a way to troubleshoot this, and I don't know enough about CORS yet. I'll report back if I find any info.

**Comment by rlamana** [comment]
Any more info about this? Closing this issue, we can reopen when more feedback is given.
