### ISSUE TITLE
Facebook return only code

### ISSUE THREAD

**Issue by iampick** [okteto/react-oauth2-login#5]
Hi,

How can I take the name , email from facebook, google, twitter

**Comment by rberrelleza** [comment]
@rlamana do you know if this is possible?

**Comment by rlamana** [comment]
It should as long as it follows the OAuth 2.0 industry-standard. I will run a couple of tests though to try to see which of the most common platforms this supports. I'll ping back with the results...

**Comment by rlamana** [comment]
I just tested it with Facebook and Google and it does work just fine 👌 

I used the sample in this repository and added the proper `clientId` and `scope`. For example for Facebook:
```
ReactDOM.render(
  <OAuth2
    authorizeUri="https://www.facebook.com/dialog/oauth"
    responseType="code"
    clientId="{you client id}"
    redirectUri="http://xxxxxxx/" // This is mandatory for facebook.
    scope="email"
    onSuccess={onSuccess}
    onFailure={onFailure}
  />,
  document.getElementById('example')
);
```
